python:
  - 2.7
  - 3.8
gsl:
  - 2.4
boost:
  - 1.69
  - 1.73
numpy:
  - 1.16.0
  - 1.19.0

zip_keys:
  - python
  - boost
  - numpy

pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
