sudo: false
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master

# services:
# 
# matrix:
#   include:
#     - os: linux
#      compiler: gcc

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - which python
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda config --add channels mcvine
  - conda install -n root conda-build
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv anaconda-client
  - source activate testenv
  - anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PASSWORD
  - conda config --set anaconda_upload yes
  - cd builders/conda
  - CORES=2 conda build .
  - cd ../..
  - conda install mcvine --use-local

script:
  - python -c "import mcvine"

notifications:
  email:
    on_success: change
    on_failure: always
