sudo: false
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master

# services:
# 
# matrix:
#   include:
#     - os: linux
#      compiler: gcc

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda config --add channels mcvine
  - conda install -n root conda-build
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv anaconda-client
  - conda install -n testenv cmake
  - conda install -n testenv pyyaml numpy
  - conda install -n testenv psutil h5py mpi4py gsl boost
  - conda install -n testenv pyre
  - conda install -n testenv danse.ins.dsm danse.ins.numpyext danse.ins.bpext
  - conda install -n testenv histogram danse.ins.matter drchops
  - conda install -n testenv mcvine-resources
  - source activate testenv
  - mkdir build
  - cd build
  - cmake ..
  - make conda-build-pkg
  - cd ..
  - conda install mcvine --use-local

script:
  - python -c "import mcvine"

notifications:
  email:
    on_success: change
    on_failure: always
