sudo: required
dist: trusty

language: cpp

branches:
  only:
    - master

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
    
before_script:
  - docker pull linjiao/mcvine-ubuntu-deps:14.04
  - git clone https://github.com/mcvine/resources.git

script:
  - docker run -v $PWD:/mcvine-src -w /mcvine-src linjiao/mcvine-ubuntu-deps:14.04  /bin/bash builders/build /mcvine-src /mcvine-build /mcvine-install /mcvine-src/resources 2
    
notifications:
  email:
    on_success: change
    on_failure: always
