sudo: false
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master

# services:
# 
# matrix:
#   include:
#     - os: linux
#      compiler: gcc

before_install:
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - export GIT_VER=`git describe --tags`
  - export VERSION=`python -c "print '$GIT_VER'.split('-')[0][1:]"`
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda config --add channels mcvine
  - conda install -n root conda-build
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv anaconda-client
  - source activate testenv
  - anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PASSWORD
  - conda config --set anaconda_upload no
  - cd builders/travis-conda
  - ./create_meta_yaml ${VERSION}unstable $GIT_FULL_HASH
  - grep version meta.yaml
  - grep git_rev meta.yaml
  - CORES=2 conda build .
  - anaconda remove -f mcvine/mcvine/dev/linux-64/mcvine-dev-py27_0.tar.bz2
  - anaconda upload /home/travis/mc/conda-bld/linux-64/mcvine-dev-py27_0.tar.bz2
  - cd ../..
  - conda install mcvine --use-local

script:
  - python -c "import mcvine"

notifications:
  email:
    on_success: change
    on_failure: always
