name: main-worklfow

env: {}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        conda-python-version: ["3.8"]
        python-version: ["3.6"]   
    steps:
      - name: install glut
        run: sudo apt-get update && sudo apt-get install -y procps freeglut3-dev libglu1-mesa unzip
        
      - name: Check out source code
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.conda-python-version }}
          activate-environment: ""
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda env list
        shell: pwsh
        run: conda env list

      - name: conda install conda-build
        shell: pwsh
        run: conda install -n root conda-build
      
      - name: build and test
        shell: pwsh
        run: PYTHONVERSION=${{ matrix.python-version }} ./builders/aws-codebuild/build_and_test.sh
